name: Weather Update

on:
  schedule:
    # Runs every day at midnight UTC
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  weather_update:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      # Install required Python packages
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      # Run the weather script
      - name: Run weather script
        run: |
          python weather_script.py
        env:
          API_KEY: ${{ secrets.OPENWEATHERMAP_API_KEY }}  # Use GitHub Secrets for API key
          CITY: "Kuwait City"  # Replace with your city if needed

      # Commit and push the changes
      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add weather_log.txt
          git commit -m "Weather log update: $(date +'%Y-%m-%d %H:%M:%S')"
          git push

