name: Daily Weather Update

on:
  schedule:
    # Runs every day at midnight UTC
    - cron: '0 0 * * *'  # Every day at midnight UTC
  workflow_dispatch:  # Allows manual trigger from GitHub UI

jobs:
  weather_update:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      # Install required Python packages
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      # Create weather_log.txt if it doesn't exist
      - name: Create weather_log.txt if not exists
        run: touch weather_log.txt

      # Run the weather script
      - name: Run weather script
        run: |
          python weather_script.py
        env:
          API_KEY: ${{ secrets.OPENWEATHERMAP_API_KEY }}  # Use GitHub Secrets for API key
          CITY: "London"  # Set city to London

      # Check for changes in the weather log file
      - name: Check for changes
        run: |
          git diff --exit-code || echo "Changes detected"

      # Commit and push the changes
      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git remote set-url origin https://github.com/${{ github.repository }}.git
          git add weather_log.txt
          git commit -m "Daily weather update for London on $(date +'%Y-%m-%d %H:%M:%S')"
          git push https://github.com/${{ github.repository }}.git HEAD:main --force
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}  # Use the GitHub secret with the token
